### PR TITLE
gentx OmniFlix-Network

### PR DESCRIPTION
**Pull request by harish551**

### CODE REVIEW

**Comment by faddat** [comment]
Can you remove genesis.json please?

I should have been doing the

digd add-genesis-account

step myself manually. Thanks!

**Comment by harish551** [comment]
> Can you remove genesis.json please?
> 
> I should have been doing the
> 
> digd add-genesis-account
> 
> step myself manually. Thanks!

sure

**Comment by harish551** [comment]
is it fine now ??

**Comment by faddat** [comment]
Yep :).  Then I'll add your coins to the genesis file.  I realized it was a problem with the directions.

**Pull request merged**
