### PR TITLE
Add Gentx BotDotNet

### PR DESCRIPTION
**Pull request by botd0tnet**
Add Gentx BotDotNet

### CODE REVIEW

**Comment by faddat** [comment]
not real sure about this / you, sorry.  

Able to provide any info on what you are aiming for in the long run and how you can help our community?

Thanks

**Comment by botd0tnet** [comment]
Too bad I cant find about address this project (tele, discord...) I see this project few weeks ago and I have been following you on twitter for a while, and also bookmarked link on github.
Today i see you accept genesis testnet, and i submit it.
Currently, I am also participating in the testnet projects on the cosmos platform ( agoric - 3 months, stargaze - 3 months, bitcanna - ended, juno, rizon, ..) and other platform ( casperlabs, polkadot)
I think I might be useful for running a testnet, as with other projects I'm working on. 
I know it's a bit late, but can I join?

**Comment by faddat** [comment]
All good.  Consider losing the barney gumble icon, but hey whatever floats your boat

**Comment by faddat** [comment]
welcome to dig, Mr. Pepe Gumble.

**Comment by faddat** [comment]
Pepe Gumble, discord is here:

https://discord.gg/pFTwq9TfQ8

**Pull request merged**
