### PR TITLE
gentx simplystaking

### PR DESCRIPTION
**Pull request by jacquesvcritien**

### CODE REVIEW

**Comment by faddat** [comment]
Not sure why this is, but your genesis is bumping out someone else's account.  Can you please try to re-create the whole thing from scratch?  thanks.  If you clone the current state of the repo, should work fine.

**Comment by faddat** [comment]
It is my fault and I'll fix it.  No action needed.

**Comment by jacquesvcritien** [comment]
Hi!

So do I have to do anything or is it sorted from your end?

**Comment by faddat** [comment]
Can you remove genesis.json please?

I should have been doing the

digd add-genesis-account

step myself manually. Thanks!

I thought it was sorted.  I was wrong, sorry bout that.

**Comment by jacquesvcritien** [comment]
I removed the genesis.json file now. Is it enough or did I miss a step?

**Comment by jacquesvcritien** [comment]
I added removed the genesis file and added the latest one so that there are not any conflicts. Is this what I had to do?

**Comment by faddat** [comment]
It'll do fine.  Sorry about flubbing the directions.  Will try and make mainnet smoother.

**Comment by jacquesvcritien** [comment]
> It'll do fine. Sorry about flubbing the directions. Will try and make mainnet smoother.

Thanks! Will be looking forward to it.

**Pull request merged**
